services:
  - type: web
    name: ntl-trading-app
    env: node
    buildCommand: npm install && npm run build && npx tsc server/index.ts --outDir dist/server
    startCommand: node dist/server/index.js
    envVars:
      - key: NODE_ENV
        value: production
